node_name = "leaf3"
node_type = "frr"

[links.eth1]
neigh = "spine1"
iface = "eth3"

[links.eth2]
neigh = "spine2"
iface = "eth3"

[linux]
net = """
# Loopbacks
ip link add dev loopback0 type dummy
ip address add 10.0.0.3/32 dev loopback0

# P2p links to spines
ip address add 10.2.1.5/31 dev eth1
ip address add 10.2.2.5/31 dev eth2
"""

[frr]
daemons = ["bfdd", "ospfd", "ospf6d"]
ospfd.instances = [1] 

net = """
interface eth1
 ip ospf 1 area 0.0.0.0
 ip ospf authentication message-digest
 ip ospf bfd
 ip ospf message-digest-key 1 md5 ABCDEFGHIJK
 ip ospf network point-to-point
 no ip ospf passive
exit
!
interface eth2
 ip ospf 1 area 0.0.0.0
 ip ospf authentication message-digest
 ip ospf bfd
 ip ospf message-digest-key 1 md5 ABCDEFGHIJK
 ip ospf network point-to-point
 no ip ospf passive
exit
!
interface loopback0
 ip ospf 1 area 0.0.0.0
exit
!
router ospf 1
 ospf router-id 10.0.0.3
 passive-interface default
exit
!
bfd
 peer 10.0.0.3
 exit
 !
exit
!
end
"""
