node_name = "spine2"
node_type = "frr"

[links.eth1]
neigh = "leaf1"
iface = "eth2"

[links.eth2]
neigh = "leaf2"
iface = "eth2"

[links.eth3]
neigh = "leaf3"
iface = "eth2"

[linux]
net = """
# Loopbacks
ip link add dev loopback0 type dummy
ip address add 10.0.2.0/32 dev loopback0

# P2p links to leafs
ip address add 10.2.2.0/31 dev eth1
ip address add 10.2.2.2/31 dev eth2
ip address add 10.2.2.4/31 dev eth3
"""

[frr]
daemons = ["bfdd", "ospfd", "ospf6d"]
ospfd.instances = [1] 

net = """
interface eth1
 ip ospf 1 area 0.0.0.0
 ip ospf authentication message-digest
 ip ospf bfd
 ip ospf message-digest-key 1 md5 ABCDEFGHIJK
 ip ospf network point-to-point
 no ip ospf passive
exit
!
interface eth2
 ip ospf 1 area 0.0.0.0
 ip ospf authentication message-digest
 ip ospf bfd
 ip ospf message-digest-key 1 md5 ABCDEFGHIJK
 ip ospf network point-to-point
 no ip ospf passive
exit
!
interface eth3
 ip ospf 1 area 0.0.0.0
 ip ospf authentication message-digest
 ip ospf bfd
 ip ospf message-digest-key 1 md5 ABCDEFGHIJK
 ip ospf network point-to-point
 no ip ospf passive
exit
!
interface loopback0
 ip ospf 1 area 0.0.0.0
exit
!
router ospf 1
 ospf router-id 10.0.2.0
 passive-interface default
exit
!
bfd
 peer 10.0.2.0
 exit
 !
exit
!
end
"""
