node_name = "t2"
node_type = "linux"
lldpd.enable = false

[links.eth1]
neigh = "sw2"
iface = "eth2"

[linux]
net = """
sysctl -w net.ipv6.conf.all.disable_ipv6=1

ip link set dev eth1 address 00:00:00:01:00:02
ip addr add 192.168.10.2/24 dev eth1

ip route replace default via 192.168.10.253 dev eth1
"""
