node_name = "leaf1"
node_type = "frr"

[links.eth1]
neigh = "spine1"
iface = "eth1"

[links.eth2]
neigh = "spine2"
iface = "eth1"

[linux]
net = """
ip route del default

# Loopbacks
ip link add dev loopback0 type dummy
ip address add 10.0.0.1/32 dev loopback0

# P2p links to spines
ip address add 10.2.1.1/31 dev eth1
ip address add 10.2.2.1/31 dev eth2

# Client link
ip address add 192.168.10.1/24 dev eth3
"""

[frr]
daemons = ["bgpd", "bfdd"]

net = """
router bgp 65000
 bgp router-id 10.0.0.1
 neighbor SPINES peer-group
 neighbor SPINES remote-as internal
 neighbor SPINES bfd
 neighbor SPINES password ibgp
 neighbor SPINES timers 1 3
 neighbor 10.2.1.0 peer-group SPINES
 neighbor 10.2.2.0 peer-group SPINES
 !
 address-family ipv4 unicast
  network 10.0.0.1/32
  redistribute connected
  maximum-paths ibgp 4
 exit-address-family
exit
!
end
"""
