node_name = "spine3"
node_type = "frr"

[links.eth1]
neigh = "leaf4"
iface = "eth1"

[links.eth2]
neigh = "leaf5"
iface = "eth1"

[links.eth3]
neigh = "leaf6"
iface = "eth1"

[links.eth4]
neigh = "spine2"
iface = "eth4"

[linux]
net = """
# Loopbacks
ip link add dev loopback0 type dummy
ip address add 10.0.3.0/32 dev loopback0

# Link to AS 65000
ip address add 20.0.0.1/31 dev eth4

# P2p links to leafs
ip address add 10.2.3.0/31 dev eth1
ip address add 10.2.3.2/31 dev eth2
ip address add 10.2.3.4/31 dev eth3
"""

[frr]
daemons = ["bgpd"]

net = """
route-map ALLOW permit 1
!
route-map RM_AS_RANGE permit 1
 match as-path PF_AS_RANGE
exit
!
router bgp 65100
 bgp router-id 10.0.3.0
 neighbor LEAFS peer-group
 neighbor LEAFS remote-as external
 neighbor LEAFS bfd
 neighbor LEAFS password ebgp
 neighbor LEAFS timers 1 3
 bgp listen range 10.0.0.0/8 peer-group LEAFS
 neighbor 20.0.0.0 remote-as 65000
 neighbor 20.0.0.0 bfd
 neighbor 20.0.0.0 password dci
 neighbor 20.0.0.0 timers 3 9
 !
 address-family ipv4 unicast
  network 10.0.3.0/32
  redistribute connected route-map RM_AS_RANGE
  neighbor LEAFS route-map RM_AS_RANGE in
  neighbor LEAFS route-map ALLOW out
  neighbor 20.0.0.0 route-map ALLOW in
  neighbor 20.0.0.0 route-map ALLOW out
  maximum-paths 4
 exit-address-family
exit
!
bgp as-path access-list PF_AS_RANGE seq 5 permit 6510[1-9]
!
end
"""
