node_name = "f"
node_type = "frr"

[links.eth1]
neigh = "leaf3"
iface = "eth3"

[linux]
net = """
ip route del default
sysctl -w net.ipv6.conf.all.disable_ipv6=1

# vrf for l3vni 10000
ip link add vrf10000 type vrf table 10000
ip link set vrf10000 up

# vrf for l3vni 20000
ip link add vrf20000 type vrf table 20000
ip link set vrf20000 up

# P2p link to leaf
ip link add link eth1 name eth1.1000 type vlan id 1000
ip link set eth1.1000 master vrf10000
ip link set eth1.1000 up
ip address add 10.169.0.1/31 dev eth1.1000
ip link add link eth1 name eth1.2000 type vlan id 2000
ip link set eth1.2000 master vrf20000
ip address add 10.170.0.1/31 dev eth1.2000
ip link set eth1.2000 up
"""

[frr]
daemons = ["bgpd", "bfdd"]

net = """
route-map RM_FW permit 1
 match ip address AL_FW
exit
!
vrf vrf10000
exit-vrf
!
vrf vrf20000
exit-vrf
!
router bgp 65000 vrf vrf10000
 bgp router-id 10.0.0.255
 neighbor LEAF peer-group
 neighbor LEAF remote-as internal
 neighbor LEAF bfd
 neighbor LEAF password ibgp
 neighbor LEAF timers 1 3
 neighbor 10.169.0.0 peer-group LEAF
 !
 address-family ipv4 unicast
  network 10.0.0.255/32
  maximum-paths ibgp 4
  redistribute connected route-map RM_FW
  import vrf vrf20000
 exit-address-family
exit
!
router bgp 65000 vrf vrf20000
 bgp router-id 10.0.0.255
 neighbor LEAF peer-group
 neighbor LEAF remote-as internal
 neighbor LEAF bfd
 neighbor LEAF password ibgp
 neighbor LEAF timers 1 3
 neighbor 10.170.0.0 peer-group LEAF
 !
 address-family ipv4 unicast
  network 10.0.0.255/32
  maximum-paths ibgp 4
  redistribute connected route-map RM_FW
  import vrf vrf10000
 exit-address-family
exit
!
access-list AL_FW seq 5 permit 192.168.10.0/24
access-list AL_FW seq 10 permit 192.168.20.0/24
access-list AL_FW seq 15 permit 192.168.30.0/24
access-list AL_FW seq 20 permit 192.168.40.0/24
!
end
"""
