node_name = "t4"
node_type = "linux"

[links.eth1]
neigh = "leaf2"
iface = "eth4"

[linux]
net = """
sysctl -w net.ipv6.conf.all.disable_ipv6=1

ip link set address 02:00:00:00:00:04 dev eth1
ip address add 192.168.40.1/24 dev eth1
ip route replace default via 192.168.40.254 dev eth1
"""
