node_name = "t1"
node_type = "linux"

[links.eth1]
neigh = "leaf1"
iface = "eth3"

[links.eth2]
neigh = "leaf2"
iface = "eth3"

[linux]
net = """
# ip address add 192.168.10.1/24 dev eth1
# ip link set dev eth1 address 00:00:00:00:00:01

ip link add dev bond0 type bond mode 802.3ad
ip link set dev bond0 up
ip link set dev eth1 down
ip link set dev eth1 master bond0
ip link set dev eth1 up
ip link set dev eth2 down
ip link set dev eth2 master bond0
ip link set dev eth2 up

ip address add 192.168.10.1/24 dev bond0
ip route replace default via 192.168.10.254
"""
